name: flutterapp
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  google_fonts: ^0.2.0
  image_picker: ^0.6.7+1
  permission_handler: ^5.0.1
  expandable_bottom_sheet: ^0.2.1+1
  url_launcher: ^5.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/